spring:
  cloud:
    openfeign:
      client:
        config:
          transfer:
            url: http://localhost:8765/transfer
          storage:
            url: http://localhost:8765/storage

api:
  basic-uri:
    storage: http://localhost:8765/storage/
    transfer: http://localhost:8765/transfer/

shop:
  account:
    id: 1

tmpVar: configServer
